select LEVEL, VALUE from SETTING s, CREDIT_CONTRACT
    WHERE CREDIT_CONTRACT.num = '001122' AND
        LEVEL = 1 OR
        LEVEL = 2 AND s.CLASS_ID = 'PRIVATE' OR
        LEVEL = 3 AND s.CLASS_ID = 'PRIVATE' AND s.FILIAL = '001' OR
        LEVEL = 4 AND s.CLASS_ID = 'PRIVATE' AND s.FILIAL = '001' AND s.FINTOOL = 'RUR'
    START WITH s.pid is null
    CONNECT BY  s.pid =  PRIOR s.ID;



select LEVEL, VALUE from SETTING s, CREDIT_CONTRACT
WHERE CREDIT_CONTRACT.num = '001122' AND
      LEVEL = 1 OR
            LEVEL = 2 AND s.CLASS_ID = 'PUBLIC' OR
            LEVEL = 3 AND s.CLASS_ID = 'PUBLIC' AND s.FILIAL = '001' OR
            LEVEL = 4 AND s.CLASS_ID = 'PUBLIC' AND s.FILIAL = '001' AND s.FINTOOL = 'RUR'
START WITH s.pid is null
CONNECT BY  s.pid =  PRIOR s.ID;



select LEVEL, VALUE from SETTING s, CREDIT_CONTRACT
WHERE CREDIT_CONTRACT.num = '001122' AND
      LEVEL = 1 OR
            LEVEL = 2 AND s.CLASS_ID = 'PRIVATE' OR
            LEVEL = 3 AND s.CLASS_ID = 'PRIVATE' AND s.FILIAL = '002' OR
            LEVEL = 4 AND s.CLASS_ID = 'PRIVATE' AND s.FILIAL = '002' AND s.FINTOOL = 'RUR'
START WITH s.pid is null
CONNECT BY  s.pid =  PRIOR s.ID;



select LEVEL, VALUE from SETTING s, CREDIT_CONTRACT
WHERE CREDIT_CONTRACT.num = '001122' AND
      LEVEL = 1 OR
            LEVEL = 2 AND s.CLASS_ID = 'PRIVATE' OR
            LEVEL = 3 AND s.CLASS_ID = 'PRIVATE' AND s.FILIAL = '001' OR
            LEVEL = 4 AND s.CLASS_ID = 'PRIVATE' AND s.FILIAL = '001' AND s.FINTOOL = 'USD'
START WITH s.pid is null
CONNECT BY  s.pid =  PRIOR s.ID;

